const MIN_LENGTH_NAME = 1;
const MAX_LENGTH_NAME = 50;
const MIN_LENGTH_CONTENT = 1;
const MAX_LENGTH_CONTENT = 1024;

export const postSchema = {
  MIN_LENGTH_NAME,
  MAX_LENGTH_NAME,
  MIN_LENGTH_CONTENT,
  MAX_LENGTH_CONTENT,
};
