const MIN_LENGTH_NAME = 1;
const MAX_LENGTH_NAME = 50;
const MIN_LENGTH_DESCRIPTION = 1;
const MAX_LENGTH_DESCRIPTION = 1024;
const MIN_VALUE_PRICE = 1;
const MAX_VALUE_PRICE = 9999999999;

export const productSchema = {
  MIN_LENGTH_NAME,
  MAX_LENGTH_NAME,
  MIN_LENGTH_DESCRIPTION,
  MAX_LENGTH_DESCRIPTION,
  MIN_VALUE_PRICE,
  MAX_VALUE_PRICE,
};

export const DEFAULT_POST_TAKE = 10;
export const DEFAULT_COMMENT_TAKE = 100;
